name: 'dbt_analytics'
version: '1.0.0'
profile: 'dbt_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
flags:
  state_modified_compare_more_than_just_body: false
  use_managed_iceberg: true
  use_concurrent_microbatch: true
  use_materialization_v2: true

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_analytics:
    +catalog: "{{ target.catalog }}"

    +grants:
      select: ["data_engineers"]

    bronze:
      +schema: bronze
      +materialized: view
      +tags: "bronze"
    staging:
      +materialized: view
      +schema: staging
      +tags: "staging"
    silver:
      +materialized: table
      +schema: silver
      +tags: "silver"
      +grants:
        select: "{{ ['data_analysts', 'data_engineers'] if target.name == 'prod' else ['data_engineers'] }}"
    gold:
      +materialized: table
      +schema: gold
      +tags: "gold"
      +grants:
        select: "{{ ['data_analysts', 'data_engineers'] if target.name == 'prod' else ['data_engineers'] }}"
    operations:
      +catalog: ops_monitoring
      +schema: auditing
      +materialized: incremental

snapshots:
  dbt_analytics:
    +meta:
      target_catalog: "{{ target.catalog }}"
    
    +target_schema: "{{ 'silver' if target.name != 'ci' else target.schema }}"