name: 'dbt_analytics'
version: '1.0.0'
profile: 'dbt_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_analytics:
    +catalog: "{{ target.catalog }}"
    
    bronze:
      +schema: bronze
      +materialized: view
      +tags: "bronze"
    staging:
      +materialized: view
      +schema: staging
      +tags: "staging"
    silver:
      +materialized: table
      +schema: silver
      +tags: "silver"
    gold:
      +materialized: table
      +schema: gold
      +tags: "gold"

snapshots:
  dbt_analytics:
    +target_catalog: "{{ target.catalog }}"
    +target_schema: silver
    +tags: "silver"