name: dbt_ci_check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_dbt_tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
      DBT_DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DBT_DATABRICKS_HTTP_PATH: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
      DBT_DATABRICKS_CLIENT_ID: ${{ secrets.DBT_DATABRICKS_CLIENT_ID }}
      DBT_DATABRICKS_CLIENT_SECRET: ${{ secrets.DBT_DATABRICKS_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Environment
        run: |
          echo "Host is set: ${{ env.DBT_DATABRICKS_HOST != '' }}"
          echo "Path is set: ${{ env.DBT_DATABRICKS_HTTP_PATH != '' }}"
          echo "Client ID is set: ${{ env.DBT_DATABRICKS_CLIENT_ID != '' }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dbt-databricks sqlfluff-templater-dbt

      - name: Install dbt packages
        working-directory: ./dbt_analytics
        run: dbt deps

      - name: Get changed files
        id: get_file_changes
        uses: tj-actions/changed-files@v42
        with:
          base_sha: main
          path: dbt_analytics
          files: |
            models/**/*.sql

      - name: Run SQLFluff
        if: steps.get_file_changes.outputs.any_changed == 'true'
        working-directory: ./dbt_analytics
        run: |
          sqlfluff lint ${{ steps.get_file_changes.outputs.all_changed_files }}


      # --- SLIM CI LOGIC ---

      - name: Restore manifest from cache
        if: github.ref != 'refs/heads/main'
        uses: actions/cache/restore@v3
        with:
          path: ./dbt_analytics/target/manifest.json 
          key: dbt-manifest-main-
          restore-keys: |
            dbt-manifest-main-

      - name: Run dbt
        working-directory: ./dbt_analytics
        run: |
          # Если файл восстановился из кэша в папку target
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "BRANCH IS MAIN: Generating clean manifest..."
            dbt compile --target prod --no-partial-parse
          elif [ -f "target/manifest.json" ]; then
            echo "Manifest found! Moving to state folder..."
            mkdir -p master_state
            mv target/manifest.json master_state/manifest.json
            
            echo "Slim CI: Running build..."
            dbt build \
              --target ci \
              --select "state:modified.body+" \
              --state master_state \
              --defer \
              --defer-state master_state \
              --favor-state
          else
            echo "CRITICAL: Manifest NOT FOUND in target/. Running full build..."
            dbt build --target ci
          fi
          
      - name: Cache manifest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/cache/save@v3
        with:
          path: ./dbt_analytics/target/manifest.json
          key: dbt-manifest-main-${{ github.run_id }}

      # --- POST-BUILD CHECKS ---

      - name: Check Source Freshness
        run: dbt source freshness
        working-directory: ./dbt_analytics

      - name: Run cleanup schema
        if: always()
        run: |
          dbt run-operation drop_ci_schema --args "{schema_name: ci_schema_${{ github.run_id }}}"
        working-directory: ./dbt_analytics