name: dbt_ci_check

# trigger on Push or Pull Request into main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_dbt_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_analytics

    steps:
      # download code
      - name: Checkout code
        uses: actions/checkout@v3

      # set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. set up dbt and Databricks adapter
      - name: Install dependencies
        run: |
          pip install dbt-databricks

      # set up connection (profiles.yml)
      - name: Setup dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_analytics:
          outputs:
            ci:
              catalog: s3_learn
              host: ${{ secrets.DBT_DATABRICKS_HOST }}
              http_path: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
              schema: staging_ci_${{ github.run_id }}
              threads: 1
              token: ${{ secrets.DBT_DATABRICKS_TOKEN }}
              type: databricks
          target: ci
          EOF

      # debug
      - name: dbt debug
        run: dbt debug

      # install dependancies
      - name: dbt deps
        run: dbt deps

      # run tests (dbt run --select state:modified+)
      - name: Run dbt tests
        run: |
          dbt seed
          dbt run 
          dbt test

      # cleanup if CI was successful
      