name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install dbt-databricks

      - name: Setup dbt Profile
        run: |
          echo "dbt_analytics:
            target: ci
            outputs:
              ci:
                type: databricks
                catalog: s3_learn
                host: ${{ secrets.DBT_DATABRICKS_HOST }}
                http_path: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
                schema: silver 
                threads: 4
                token: ${{ secrets.DBT_DATABRICKS_TOKEN }}" > ./dbt_analytics/profiles.yml

      - name: Generate Docs
        working-directory: ./dbt_analytics
        run: |
          dbt deps
          dbt docs generate

      - name: Prepare static files
        run: |
          mkdir -p public
          cp dbt_analytics/target/index.html public/
          cp dbt_analytics/target/manifest.json public/
          cp dbt_analytics/target/catalog.json public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4