name: Scheduled dbt Run with Custom Alerts

on:
  schedule:
    - cron: '0 6 * * *' # Каждый день в 6 утра
  workflow_dispatch:

jobs:
  run-and-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-databricks requests python-dotenv

      - name: Setup dbt Profile
        # Используем ту же структуру, что и в docs-workflow, но меняем target на dev
        run: |
          mkdir -p ~/.dbt
          echo "dbt_analytics:
            target: dev
            outputs:
              dev:
                type: databricks
                catalog: s3_learn
                host: ${{ secrets.DBT_DATABRICKS_HOST }}
                http_path: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
                schema: bronze
                threads: 1
                token: ${{ secrets.DBT_DATABRICKS_TOKEN }}" > ./dbt_analytics/profiles.yml

      - name: Run dbt Build
        id: dbt_run
        continue-on-error: true 
        working-directory: ./dbt_analytics
        run: |
          dbt deps
          # Запускаем полный билд (Bronze + Silver + Gold + Tests)
          dbt build --target dev
          dbt snapshot --target dev

      - name: Send Custom Telegram Alert
        if: always() 
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_RESULTS_PATH: ./dbt_analytics/target/run_results.json
        run: |
          python run.py
      - name: Debug run_results.json
        run: |
          echo "Current directory:"
          pwd
          echo "Check if file exists:"
          ls -l ./dbt_analytics/target/run_results.json
          echo "--- SHOWING RUN RESULTS (first 50 lines) ---"
          head -n 50 ./dbt_analytics/target/run_results.json