name: Scheduled dbt Run with Custom Alerts

on:
  schedule:
    - cron: '0 6 * * *' # Каждый день в 6 утра
  workflow_dispatch:

jobs:
  run-and-alert:
    runs-on: ubuntu-latest

    env:
      DBT_DATABRICKS_HOST: ${{ secrets.DBT_DATABRICKS_HOST }}
      DBT_DATABRICKS_HTTP_PATH: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
      DBT_DATABRICKS_CLIENT_ID: ${{ secrets.DBT_DATABRICKS_CLIENT_ID }}
      DBT_DATABRICKS_CLIENT_SECRET: ${{ secrets.DBT_DATABRICKS_CLIENT_SECRET }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-databricks requests python-dotenv

      - name: Run dbt Build
        id: dbt_run
        continue-on-error: true 
        working-directory: ./dbt_analytics
        run: |
          dbt deps
          
          echo "Step 1: Ingesting new data from S3 to Bronze..."
          dbt run-operation load_all_sources --target prod
          
          echo "Step 2: Building Medallion layers (Silver -> Gold)..."
          dbt build --target prod
        
      - name: Check Source Freshness
        run: dbt source freshness --target prod
        working-directory: ./dbt_analytics

      - name: Send Custom Telegram Alert
        if: always() 
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_RESULTS_PATH: ./dbt_analytics/target/run_results.json
        run: |
          python run.py